#!/system/bin/sh

echo "noop" > /sys/block/mmcblk0/queue/scheduler
echo "noop" > /sys/block/mmcblk0boot0/queue/scheduler
echo "noop" > /sys/block/mmcblk0boot1/queue/scheduler
echo "noop" > /sys/block/mmcblk0rpmb/queue/scheduler
