#!/system/bin/sh

echo 5000000 > /proc/sys/vm/dirty_background_bytes
echo 5000000 > /proc/sys/vm/dirty_bytes
echo 85 > /proc/sys/vm/overcommit_ratio

# low thresholds for LMK
echo 8192,16384,32768,32768,49536,65536 > /sys/module/lowmemorykiller/parameters/minfree

# don't try to keep too much memory free
echo 1024 > /proc/sys/vm/extra_free_kbytes